version: "3.9"  
services:
  ansible:
    build: 
      context: ./ansible_base
      dockerfile: Dockerfile
    container_name: ansible_controller
    volumes:
      - type: bind
        source: ../capstone_project
        target: /home/ansible_controller/capstone_project
  target1:
    build: 
      context: ./ansible_base
      dockerfile: Dockerfile
    container_name: ansible_target1

  target2:
    build: 
      context: ./ansible_base
      dockerfile: Dockerfile
    container_name: ansible_target2
hiasdfjnkmszdxlf jkmsdxf
