- name: Update Node.js application to display "Hello DevOps!"
  hosts: localhost
  become: true

  tasks:
    - name: Update app.js file
      replace:
        path: /home/ansible_controller/capstone_project/hello-world/src/App.js
        regexp: 'Hello World!'
        replace: 'Hello DevOps!'

    - name: Restart Node.js service
      systemd:
        name: nodejs.service
        state: restarted

