name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd .. && dir * && \
          npm install

      - name: Run tests
        run: |
          npm test

      - name: Build container
        if: success()
        run: |
          docker build -t my-react-app .

